### ISSUE TITLE
The curious case of the ASTRA adjoint on GPU

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#103]
The ASTRA Toolbox GPU back projector is known to not be a highly accurate adjoint to the forward operator. In the old days, we handled this with a generous tolerance on our adjoint test. After some improvements to that adjoint test, the ASTRA back projector fails _very_ hard (relative error 0.78).

The question: is this a problem with the test, our interface to ASTRA, or ASTRA itself? If it's the latter, let's just skip these tests on GPU.

First step: get a GPU install of SCICO and run `pytest scico/test/linop/test_radon_astra.py` to see if the failures occur for you.

**Comment by lukepfister** [comment]
IIRC it’s a problem with the astra algorithm itself.

**Comment by smajee** [comment]
So if it is due to the inaccuracy of the astra projector, should we increase the tolerance of the test or just disable them for gpu?

**Comment by Michael-T-McCann** [comment]
To clarify: we know there is _at least_ a problem with the ASTRA GPU backprojection algorithm itself. The question here why is the new adjoint test failing with a relative error approaching one. I didn't think the ASTRA backprojection was _that_ inaccurate, but I don't have a good intuition for our new adjoint test.

If you are convinced there is no bug in the interface or test, I learn toward increasing the tolerance rather than disabling the test, because it might allow us to catch regressions in the interface in the future.

**Comment by lukepfister** [comment]
has the astra version changed? it looks like they finally shipped v2 (was on 1.9.9 beta for a looong time)

has the jax/jaxlib version changed?  might be worth seeing if something has been modified in the host_callback interface;  it is marked as "experimental" and subject to breaking changes

**Comment by smajee** [comment]
Is the adjoint test new? Did it ever pass on GPU for astra?

**Comment by lukepfister** [comment]
No, it isn't new.  It passed with very, very loose tolerances; like a relative error of 20% or something.

Sounds like that's no longer the case (and I have no gpu machine to test)

**Comment by smajee** [comment]
I did pytests on old commits to see where it broke on GPU.
It seems the tests pass on commit d86b51f and fail after commit 656f59d (Improve LinearOperator adjoint tests (#72)).

That commit seems to be the one where a new adjoint test (`adjoint_test`) was introduced. The old `adjoint_AAt_test` seems to pass on GPU.

I don't understand the tests well enough to comment on where why one passes and the other fails. Any ideas?

**Comment by Michael-T-McCann** [comment]
Seems clear that what is needed is just a looser tolerance. The tolerance
values for the new and old tests mean different things, so this is not too
surprising.

**Comment by smajee** [comment]
That sounds like a reasonable solution to me.

It seems currently all the astra tests use the same tolerance irrespective of the test. I found that I can make the test pass by making the tolerance of `adjoint_test` 15 times. I have pushed the change in a pull request. Let me know your comments on the pull request.
