### ISSUE TITLE
`jit`ing the `DnCNN` prox on GPU

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#104]
When  I run `pytest scico/test/test_functional.py -k DnCNN` with a GPU install of SCICO, I get a failure in `TestDnCNN.test_prox`, which is comparing the `jit`ed to un`jit`ed version of the DnCNN prox. These results are disturbingly different:

    E       Mismatched elements: 1020 / 1024 (99.6%)
    E       Max absolute difference: 0.70825666
    E       Max relative difference: 83.99731
    E        x: array([[-1.311581e+00, -4.477247e-01, -2.993065e-01, ...,  1.231516e-01,
    E                2.924881e-01,  1.054722e-01],
    E              [ 2.548240e-01,  7.504759e-01, -3.427111e-01, ...,  1.717497e-01,...
    E        y: array([[-1.290338, -0.550369, -0.359681, ...,  0.004449,  0.33103 ,
    E                0.088125],
    E              [ 0.211299,  0.899408, -0.37546 , ...,  0.460677, -0.817596,...

Might this be a JAX bug? One could try bumping the jax version and see if it is fixed.

**Comment by lukepfister** [comment]
A jax bug is possible, but I’d start by looking to see if the code (init or eval) has any side effects that are being missed by the jit. 

You could do something like
jax.jit(lambda x: f.prox(x)) and see if it matches f.prox(x). That is, jit the fully instantiated denoiser object.

**Comment by FernandoDavis** [comment]
Thanks Luke! I'll try to debug it tomorrow and keep that in mind!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by crstngc** [comment]
The issue seems to be related to the fact that Jax is non deterministic on GPU as discussed in 
https://github.com/google/flax/issues/33#issuecomment-595885662
https://github.com/google/jax/issues/565 and https://github.com/google/jax/issues/4823

**Comment by crstngc** [comment]
Branch `cristina/jitDnCNNprox` includes a fix to the `DnCNN` tests in `test_functional.py` as suggested in https://github.com/google/jax/issues/4823#issuecomment-735297795. @Michael-T-McCann could you please check it?

**Comment by crstngc** [comment]
It could be that this changes when they push an updated jaxlib as mentioned in https://github.com/google/jax/issues/565#issuecomment-966513644

**Comment by lukepfister** [comment]
great catch folks.  that is way worse than i'd expect from gpu nondeterminisim!  (fwiw most things on a gpu are nondeterministic unless specifically instructed otherwise)
