### ISSUE TITLE
API docs for scico.solver

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#109]
Some issues related to the API docs for the `scico.solver` module:

- [x] There is still a `.. todo:` in the module header docstring.
- [x] There are two instances of `TODO` comments in the code (see #96).
- [x] Docstrings for `scipy.optimize.minimize` and `scipy.optimize.minimize_scalar` are explicitly included. Is there a good reason for doing this instead of adopting the strategy followed for  `scico.numpy` (i.e. automatically attach the docstrings when running sphinx)?
- [x] The split and join functions should be made private

**Comment by lukepfister** [comment]
Re: 3rd point, go ahead and do it automatically. Be sure to leave the part describing the differences! eg the part “This function differs from scipy.optimize.minimize in three ways…”

**Comment by lukepfister** [comment]
Would also suggest making the split/join functions private, or moving them to a utils module.

**Comment by bwohlberg** [comment]
Automatic inclusion of the docs from `scipy.optimize` is greatly complicated by the inclusion of only part of the docstring. One could make it work, but it would be pretty fragile. I'm strongly leaning towards just removing the explicit copy (which is a maintenance nightmare) and relying on the cross-reference to the full docs.

**Comment by bwohlberg** [comment]
Some tasks pushed to #123 and #124.
