### ISSUE TITLE
Additional optimizers should be added to scico.solver

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#124]
These notes are taken from a *ToDo* note that has been removed from `scico.solver`:

Use jax to compute Hessian-vector products for use in Newton methods. See https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Hessian-vector-products-using-both-forward--and-reverse-mode for examples of constructing Hessians in jax.

**Comment by bwohlberg** [comment]
See also #196.

**Comment by bwohlberg** [comment]
See also #232.

**Comment by Michael-T-McCann** [comment]
Moved to the internal list of long-term projects.
