### ISSUE TITLE
Consider removal of jaxlib/jax version tests in scico/__init__.py

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#138]
The main package `__init__.py` file currently includes tests for the appropriate `jaxlib` and `jax` versions. As indicated in the TODO comment in that file, these should be considered for removal.

It's also worth noting that these tests currently just apply a great-than-or-equal version number test, while the requirements file pins the versions to specific values. If a decision is made to keep these tests, consistency in this regard would seem to make sense.

**Comment by Michael-T-McCann** [comment]
+1 on removing the checks, I think they are now redundant.

**Comment by Michael-T-McCann** [comment]
By vote in a dev meeting, let's leave the check there.
