### ISSUE TITLE
Expand `scico.numpy` ufunc list

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#147]
[Universal functions (ufuncs)](https://numpy.org/doc/stable/reference/ufuncs.html) are functions that are applied elementwise on arrays. These should be very easy to make work on `BlockArrays`, but currently only the following are supported in `scico.numpy`:

https://github.com/lanl/scico/blob/912bb9e2762af3e6083deb62a9e53b7425c2979c/scico/numpy/__init__.py#L90-L105

Eventually, we'd like to have every [ufunc from numpy](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs) that is [currently implemented in jax](https://jax.readthedocs.io/en/latest/jax.numpy.html). (I think) this is only requires cross-checking these lists and adding to `_ufunc_functions` in `numpy/__init__.py`.

**Comment by bwohlberg** [comment]
@Michael-T-McCann: Was this perhaps resolved in #259?

**Comment by Michael-T-McCann** [comment]
> @Michael-T-McCann: Was this perhaps resolved in #259?

#259 added significantly to this list. I don't think every possible (or even reasonable) `jax.numpy` function is wrapped, but most are.

**Comment by bwohlberg** [comment]
OK. Closing for now.
