### ISSUE TITLE
High GPU memory usage

### ISSUE THREAD

**Issue by Kokoing123** [lanl/scico#161]
when I use ADMM to slove the problem, the GPU memory was largely occupied, but I thought it should not use too much.
is there any reason about it? and any ways to reduce the GPU memory useage?

**Comment by bwohlberg** [comment]
If your problem is much smaller than the available GPU memory, this is most likely due to [GPU memory pre-allocation](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html). You can disable it by setting environment variable `XLA_PYTHON_CLIENT_PREALLOCATE=false`.

**Comment by bwohlberg** [comment]
I'm going to assume that the response resolves the question an close this issue. Please re-open if you have any additional questions or comments.

**Comment by Kokoing123** [comment]
thank you very much, your solution was worked, and I used the 'XLA_PYTHON_CLIENT_MEM_FRACTION' to limited gpu use.
