### ISSUE TITLE
Check for copies in `BlockArray` indexing

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#172]
(Based on a TODO in the code)
A particular type of block arraying indexing may result in copies, we'd like to confirm whether it does or not:
https://github.com/lanl/scico/blob/ce4947e14a442b8d0daa86e05f7dd6900223a769/scico/blockarray.py#L1323-L1326

_Originally posted by @bwohlberg in https://github.com/lanl/scico/pull/150#discussion_r781658870_

**Comment by bwohlberg** [comment]
This was previously https://github.com/lanl/scico/blob/ffec40b25ed1fca18a3b9a31103d5612b68884a5/scico/blockarray.py#L1316-L1318

The `TODO` implies the need to check whether the operation creates copies. It's not clear what the intended action was if this was confirmed.

@lukepfister: Can you clarify what's going on here?

**Comment by lukepfister** [comment]
It needs to be checked.

The final array() call definitely makes a copy (all BlockArray constructors
involve a copy).

The note is to investigate if each of the .ats do too. I think that it does
involve a copy, as there really isn’t a notion of a “view” in Jax.

Stated another way, I think that each item on the list comprehension is a
copy, then a final copy puts them in a contiguous array

**Comment by bwohlberg** [comment]
And what's the overall purpose of checking. Just to ensure that it's correctly documented, or was there some other action to be taken depending on the outcome of this check?

**Comment by lukepfister** [comment]
Documented, and possibly try to find a different implementation to reduce
copies

**Comment by FernandoDavis** [comment]
This is non longer necessary due to the changes in BlockArray. Ellipsis indexing is no longer a thing due to it being list based. It only supports integers or slices.

**Comment by Michael-T-McCann** [comment]
I think it's safe to say this is an ancient TODO that is no longer relevant given the changes in BlockArray since.
