### ISSUE TITLE
Add jaxopt

### ISSUE THREAD

**Issue by lukepfister** [lanl/scico#196]
I believe that improvements to optimization algorithms are going in this package, rather than the jax core.

https://twitter.com/mblondel_ml/status/1488166454662946820?s=21

**Comment by bwohlberg** [comment]
Direct links to [github repo](https://github.com/google/jaxopt) and [docs](https://jaxopt.github.io/stable/).

**Comment by lukepfister** [comment]
Thanks Brendt. I originally linked the tweet because I’m interested in the answer to this question https://twitter.com/ogrisel/status/1488169435982618636?s=21

**Comment by Michael-T-McCann** [comment]
Moved to the internal list of long-term projects.
