### ISSUE TITLE
Double-space after period.

### ISSUE THREAD

**Issue by tbalke** [lanl/scico#203]
There still seem to be instances of this in
```
README.rst
docs/source/conf.py
docs/source/contributing.rst
docs/source/functional.rst
docs/source/notes.rst
docs/source/operator.rst
docs/source/overview.rst
docs/source/style.rst
examples/scripts/demosaic_ppp_bm3d_admm.py
examples/scripts/sparsecode_poisson_blkarr_pgm.py
scico/_generic_operators.py
scico/blockarray.py
scico/loss.py
scico/util.py
scico/functional/_functional.py
scico/linop/optics.py
scico/linop/radon_astra.py
scico/optimize/admm.py
```

@bwohlberg @Michael-T-McCann

**Comment by Michael-T-McCann** [comment]
I welcome this renewed interest in standards! I don't think we have a standard defined on this and I don't think we need one, as I can't think of a case where it would be user-facing.

In my Midwestern American school experience (late 90s, early 2000s) we were taught to use two spaces. I quickly dropped the habit upon realizing it didn't matter in modern document creation tools.
