### ISSUE TITLE
Unchecked assumptions on attribute type

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#215]
This line implicitly assumes that `A` is a `LinearOperator`
https://github.com/lanl/scico/blob/2b7a693234a06f27bea7fc7d52f3a1e7b41c08ea/scico/loss.py#L195
but according to the typing on the `A` parameter of the class `__init__`, 
https://github.com/lanl/scico/blob/2b7a693234a06f27bea7fc7d52f3a1e7b41c08ea/scico/loss.py#L124
`A` may also be a function, which does not have an `adj` method. 

The `prox` method needs some additional checking to ensure that `A` is a `LinearOperator`, raising an exception if it is not.

**Comment by tbalke** [comment]
Good catch. I'll fix it
