### ISSUE TITLE
blockarray docs inconsistency

### ISSUE THREAD

**Issue by Michael-T-McCann** [lanl/scico#238]
In the blockarray docs, the examples in https://scico.readthedocs.io/en/latest/_autosummary/scico.blockarray.html#numpy-ufuncs don't seem to match between code and math, especially the `snp.sum(x, axis=2)`. We should check these.

Also, why does/should `snp.sum(x, axis=2)` work at all when `snp.sum(x[1].shape, 1)` gives an error? Similarly, why does `snp.sum(x, axis=99)` work?

**Comment by bwohlberg** [comment]
@Michael-T-McCann: was this not resolved by #259?
