### ISSUE TITLE
Support fan beam geometry options of svmbir

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#241]
There is now support for fan beam geometry in the svmbir pre-release branch (see cabouman/svmbir#231). The interface in `linop.radon_svmbir` should be extended to support it.

**Comment by smajee** [comment]
As per discussion, ParallelBeamProjector should be renamed to TomographicProjector in order to support to fan beam.

**Comment by smajee** [comment]
> This is urgent now since the recent `svmbir` release seems to have broken the`scico` interface to `svmbir`.

Got it.

**Comment by smajee** [comment]
The urgent parts have been addressed via PR #246 https://scico.readthedocs.io/en/latest/examples/ct_svmbir_ppp_bm3d_admm_prox.html

**Comment by smajee** [comment]
Fixed in PR #252
