### ISSUE TITLE
Docs for `scico.linop.svmbir` are inadequate

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#244]
The docs for `scico.linop.svmbir` need improvement. Examples of important information that is currently omitted are the supported input shapes (2D or 3D) and the role of each axis in each case. Also, is ``num_channels`` really the "number of pixels in the sinogram"? Some of this documentation improvement can be achieved by reference to `svmbir` docs, but it should be via reference to specific functions rather than a link to the entire project.

**Comment by smajee** [comment]
Issue #182 also has some comments stating similar docs inaccuracies. Would be good to cloese them together.

**Comment by smajee** [comment]
Fixed in PR #252
