### ISSUE TITLE
ADMM weighted tv issue with weighted function setup

### ISSUE THREAD

**Issue by samdporter** [lanl/scico#280]
https://github.com/lanl/scico/blob/4381be51efda22696bdcd925e5555b7614c8ce92/examples/scripts/ct_astra_weighted_tv_admm.py#L147

Should this be `f = loss.WeightedSquaredL2Loss(y=y, A=A, W=linop.Diagonal(weights))`?

**Comment by tbalke** [comment]
There is no `WeightedSquaredL2Loss` any more. This functionality has been absorbed by `SquaredL2Loss`.

**Comment by samdporter** [comment]
OK thanks. I think the pip install might not use the most recent release, then.
Running this script threw an error that required the above change

**Comment by bwohlberg** [comment]
Thanks for taking the time to create an issue on this. While it isn't a bug in the code, it is helpful to know when others encounter problems in using the package.

Yes, if you install from pypi you get the most recent release, which often has significant differences from the current development version on gitub. Did you install the package via pip and then download the examples from github? If so, any suggestions as to where would be the best place to add a warning about the possible version mimatch?

**Comment by bwohlberg** [comment]
Closing as resolved.

**Comment by bwohlberg** [comment]
No problem, and thanks for the clarification.
