### ISSUE TITLE
UserWarning in tests

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#32]
Some of the tests (e.g. in `scico/test/test_admm.py`) generate warnings such as
```
scico/scico/loss.py:122: UserWarning: Argument 1 of 1 is an np.ndarray. Will cast it to DeviceArray. To suppress this warning cast all np.ndarrays to DeviceArray first.
    y = ensure_on_device(y)
```

**Comment by FernandoDavis** [comment]
I saw it was assigned to Luke and Mike, but if they have enough on their plate and changing relevant arrays is the only thing needed, I can maybe tackle this by Monday.
