### ISSUE TITLE
Stacking operators derived from `Operator` rather than `LinearOperator`?

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#326]
Is there good reason for the `VerticalStack` and `DiagonalStack` operators to be children of `LinearOperator` rather than `Operator` ? The current arrangement prevents them from being used to stack `Operator` objects that are not instances of `LinearOperator`, for which they are also potentially useful.

**Comment by Michael-T-McCann** [comment]
I am aware of no good reason for them to be in `LinearOperator` rather than `Operator`.

**Comment by bwohlberg** [comment]
It looks as if the use of `_wrap_add_sub` by `VerticalStack` would complicate modifying it to be a stack of `Operator`. Any suggestions?

**Comment by Michael-T-McCann** [comment]
`_wrap_add_sub` is defined in `scico._generic_operators` , so I don't see a circular import problem. And it seems like the operation of adding two vertical stacks of operators is well-defined. Where does the complexity come from?

**Comment by bwohlberg** [comment]
See PR #329, which would preceed this change.

**Comment by Michael-T-McCann** [comment]
Ah. That might be a reason why we can't refactor it like this. Currently whether an operator is linear is denoted by its class. If we want to have both linear and nonlinear stacks, we'll need a class for each.

**Comment by bwohlberg** [comment]
I think having both stack classes be derived from `Operator` could be made to work, but including code specifically for a derived class is not great OO design. Perhaps the simplest approach for now is to derive `DiagonalStack` from `Operator` (since it doesn't have any `LinearOperator` specific components), and leave `VerticalStack` as being derived from `LinearOperator`?

**Comment by Michael-T-McCann** [comment]
Consider any place that we want to check if an operator is linear, e.g.,
https://github.com/lanl/scico/blob/88026d2833c62dbde1edd635eb6a8dd982aecf0f/scico/optimize/_admmaux.py#L199-L203

If `DiagonalStack` derives from `Operator`, diagonal stacks of `LinearOperator`s would raise this error.

**Comment by bwohlberg** [comment]
Good point. So then the only practical option would be to have both `Operator` and `LinearOperator` versions of the stack classes?
