### ISSUE TITLE
GPU installation update for SCICO

### ISSUE THREAD

**Issue by FernandoDavis** [lanl/scico#334]
While helping Maliha, from the Imaging Lab @ Purdue, install SCICO with GPU today I found the following error in the guide:

![image](https://user-images.githubusercontent.com/33134709/188733491-b1d3f6ab-869c-4a74-84ac-0f5fda3b251d.png)

It says the following:

![image](https://user-images.githubusercontent.com/33134709/188733567-4ab8608b-8406-4cf2-8fad-aa3e60017870.png)

To fix it all I did was update:

`pip install --upgrade "jaxlib==0.3.0+cuda11.cudnn805" -f https://storage.googleapis.com/jax-releases/jax_releases.html`

to:

`pip install "jaxlib==0.3.0+cuda11.cudnn805" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

This was the result:

![image](https://user-images.githubusercontent.com/33134709/188733788-e0720050-8513-45aa-a632-ef89da020422.png)

**Comment by bwohlberg** [comment]
The significant change is in the URL for the packages? Does this still work if we keep the `--upgrade` argument to `pip`?

**Comment by FernandoDavis** [comment]
Yeah, it was something minor, I can re-do the installation and test if the upgrade argument is still fine.

**Comment by FernandoDavis** [comment]
Works just fine with the --upgrade argument as long as cuda is added to the url! So it should be an easy fix to the install doc.

**Comment by bwohlberg** [comment]
Thanks for checking. I'll make the change to the docs.

**Comment by FernandoDavis** [comment]
Ah ill delete the other PR, I think we did it at the same time haha.
