### ISSUE TITLE
Apparent error in docstring for `Operator.__init__`

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#335]
There appears to be an error in the docstring for  `Operator.__init__` :

https://github.com/lanl/scico/blob/88026d2833c62dbde1edd635eb6a8dd982aecf0f/scico/operator/_operator.py#L88-L90

If I'm not mistaken, it should state "... then `self._eval` must be defined ...".

@Michael-T-McCann: do you agree?

**Comment by Michael-T-McCann** [comment]
> @Michael-T-McCann: do you agree?

Agreed.

Even with that fixed, I find it mightily confusing. Perhaps "Required unless `__init__` is being called from a derived class with an `_eval` method." Whether this is a good design is a separate question.

Another positive change we could make: `H = Operator((10,))` currently throws the error `AttributeError: 'Operator' object has no attribute '_eval'`. Instead, `__init__` could check if `eval_fn` is not passed and `self._eval` is not defined and throw an error.

**Comment by bwohlberg** [comment]
> Even with that fixed, I find it mightily confusing. Perhaps "Required unless `__init__` is being called from a derived class with an `_eval` method." 

That's quite a bit better.

> Whether this is a good design is a separate question.

Agreed, but I'm inclined to leave that issue alone for now.

> Another positive change we could make: `H = Operator((10,))` currently throws the error `AttributeError: 'Operator' object has no attribute '_eval'`. Instead, `__init__` could check if `eval_fn` is not passed and `self._eval` is not defined and throw an error.

I was thinking of that too. Will do.
