### ISSUE TITLE
problem with cv2.remap in linop.LinearOperator

### ISSUE THREAD

**Issue by matinaz** [lanl/scico#387]
Hello,

I am trying to use the result of cv2.remap in linop.LinearOperator, in order to do image warping, but it is not working. Is it possible?

Thank you in advance.

**Comment by bwohlberg** [comment]
It's difficult to answer such a broad question. Could you provide some more detail?

**Comment by matinaz** [comment]
We want to use scico for video super-resolution, so we need an operator that does per pixel shift, followed by downsampling. We used cv2.remap for the shift but it gives an error:

 _"raise TracerArrayConversionError(self)
jax._src.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float32[576,720,3]):JaxprTrace(level=1/0)>
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError"_

What would be the best way to implement the per-pixel shift in the operator?

Thank you in advance.

**Comment by bwohlberg** [comment]
Unless you implement your own adjoint operator, `linop.LinearOperator` tries to use jax autograd features to define it, which is going to be problematic when you're calling code like `cv2.remap`, which is, I believe, based on an interface to an underlying C/C++ library. The simplest solution is going to be to implement the shift and downsampling using `jax.numpy` (or `scico.numpy`) functions. I assume you need sub-pixel shifts, which should be achievable using `jax.scipy.ndimage.map_coordinates`. If that isn't suitable for some reason, you could also take a look at [jaxinterp2d](https://github.com/adam-coogan/jaxinterp2d/). The downsampling should be trivial to achieve via indexing.
