### ISSUE TITLE
New typing errors with recent version of `mypy`

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#388]
Recent versions of `mypy` (e.g. 1.1.1 as well as some earlier versions) are producing errors in existing code that presumably passed the `mypy` CI when committed:
```
scico/flax/examples/examples.py:258: error: Argument 3 to "runtime_error" has incompatible type "Union[ndarray[Any, Any], Any]"; expected "Union[int, float]"  [arg-type]
scico/flax/examples/examples.py:261: error: Argument 3 to "runtime_error" has incompatible type "Union[ndarray[Any, Any], Any]"; expected "Union[int, float]"  [arg-type]
Found 2 errors in 1 file (checked 80 source files)
```

The problem appears to be that parameters `requested` and `available` of function `runtime_error` in `scico/flax/examples/examples.py` are declared as having type `Union[int, float]`, but are passed ndarrays when called within function `load_foam1_blur_data`, in the same module. What is the preferred solution? Simply expand the types for  `requested` and `available`? This doesn't seem entirely desirable since `runtime_error` includes these values (which could be large) in the string used to construct the `RuntimeError` exception. Alternatively, was the intent to just pass a single scalar value from e.g. `blur_kernel` and `blur_train` to `runtime_error`? This would avoid the typing error as well as the potentially large exception description string, but it's not clear that including just a single scalar value from a large array is very useful.

Note that a number of other apparently-new typing errors have already been corrected in branch `brendt/mypy`.

**Comment by crstngc** [comment]
Yes, the intent was to compare the whole `blur_kernel` array, hence the `np.allclose`, and, if different, just pass a single scalar value from `blur_kernel` and `blur_train` (or `blur_test`) to the `runtime_error`. Perhaps it would be more robust to use the max value in the error report. It seems a compromise of not reporting all the values, which could be large and difficult to parse by an user, and give at least an indication of the magnitude of the difference.

**Comment by bwohlberg** [comment]
Proposed solution here
https://github.com/lanl/scico/blob/c69b654c61d758229ae5e104443490d2c13787ce/scico/flax/examples/examples.py#L255-L261
and here
https://github.com/lanl/scico/blob/c69b654c61d758229ae5e104443490d2c13787ce/scico/flax/examples/examples.py#L664-L703

Please check that this make sense. Please also check the string formatting in `runtime_error_array`: I didn't really understand the point of the formatting specifiers in the constant string components.

**Comment by crstngc** [comment]
The proposed solution makes sense. The formatting in the error in `runtime_error_array` should be updated to
```
raise RuntimeError(
     f"{'Requested parameter --':15s}{type}{'--'}"
     f"{' does not match parameter read from '}"
     f"{idstring}{' file'}. Maximum array difference: {maxdiff:>5.3f}."
     f"\nDelete cache and check data source."
)
```
