### ISSUE TITLE
`norm(...)**2` in `GenericSubproblemSolver` causes `nan`s in gradients

### ISSUE THREAD

**Issue by Sibgatulin** [lanl/scico#395]
Currently `GenericSubproblemSolver.solve()` [defines](https://github.com/lanl/scico/blob/013d696a1648df20130ae71e5adf0e422395a38c/scico/optimize/_admmaux.py#L101) the objective in terms of `norm(zi-ui-Ci(x))**2` which is [advised against](https://scico.readthedocs.io/en/latest/notes.html#non-differentiable-functionals) in the docs. Just as suggested, such objective can (and does) lead to `nan`s in the gradient, causing the solution to silently remain at the initial `x0`. Using the recommended `snp.sum((zi-ui-Ci(x))**2)` seem to do the trick. I have a little illustrative example [here](https://gist.github.com/Sibgatulin/99c08ae927be09e31cd8b84800c0a597).
Is there any downside to using `snp.sum`?

**Comment by Sibgatulin** [comment]
Thanks for addressing it so quickly, and for the hint to use `PDHG` or `NonLinearPADMM`, I'll give it a try.
And I do remember seeing a warning regarding the size of a problem, suitable for `GenericSubproblemSolver`, I think a user is well cautioned. My intention was to get a kind of a baseline and then to try and see if I could maybe make use of [jaxopt](https://jaxopt.github.io/stable/unconstrained.html#solvers) instead of `scipy.minimize`...

**Comment by bwohlberg** [comment]
Integrating jaxopt has been on our todo list for some time (see #196), but we have not yet been able to find the time to do so.
