### ISSUE TITLE
One test failing with jax 0.4.8 and jaxlib 0.4.7 on GPU

### ISSUE THREAD

**Issue by crstngc** [lanl/scico#406]
`test_crop_pad_adjoint`, for `Pad` and `Crop` linear operators, is failing for one case:

FAILED scico/test/linop/test_func.py::test_crop_pad_adjoint[pad2] - AssertionError: assert Array(False, dtype=bool)

when testing on GPU with jax 0.4.8 and jaxlib 0.4.7.

**Comment by bwohlberg** [comment]
Resolved by #399.
