### ISSUE TITLE
Proximal operator for a custom prior

### ISSUE THREAD

**Issue by matinaz** [lanl/scico#437]
We want to solve an inverse problem with a custom prior, so we created a new Functional with our prior as evaluation function. However, ADMM solver needs a proximal operator, but our prior is complicated, so it is not clear how to evaluate it analytically. Is there a way to evaluate it using SCICO, or is there any solver implemented in SCICO apart from ADMM that does not require a proximal operator?

**Comment by bwohlberg** [comment]
There are a number of other algorithms other than ADMM in `scico.optimize`, but they're all proximal algorithms that depend on your functional having an efficiently computable proximal operator. In principle you could use `scico.solver.minimize` (a wrapper for `scipy.optimize.minimize`) to compute the proximal operator, but that wouldn't be feasible for anything other than a really small-scale problem.

Without knowing more about your prior functional, the best I can suggest would be to try a minimizer like `jaxopt.LBFGS` from the `jaxopt` package applied to the entire inverse problem functional.

**Comment by bwohlberg** [comment]
Closing as resolved. Feel free to re-open if you have further questions.

**Comment by matinaz** [comment]
Yes, it is.

Στις Παρ 8 Σεπ 2023 στις 5:48 μ.μ., ο/η Brendt Wohlberg <
***@***.***> έγραψε:

**Comment by bwohlberg** [comment]
I'm afraid I don't see any simple solutions. Most proximal algorithms will use a proximal operator for `g`, but it's going to be very slow if the prox is not efficiently implemented. It may be worth a careful look at the function to see if there is any way of designing a relatively efficient prox, but my guess is that it will be difficult or impossible.

**Comment by matinaz** [comment]
This is our opinion too. Thank you so much for trying, we will search it a lit bit more and if we figure out any efficient solution we'll let you know.

**Comment by bwohlberg** [comment]
One option that may not be possible, but that is perhaps worth considering: can you express your functional in the form
$$g(x) = h(A(x))$$
where $h$ is a simple prox-friendly functional, and $A$ is a non-linear operator implemented in JAX so that it can be auto-differentiated? If so, you should be able to use the `scico` Non-linear Proximal ADMM solver to solve the problem.

**Comment by matinaz** [comment]
Well, we managed to implement g(x)=h(A(x)), but we solve h(A(x)) at once, since we don't have A(x), and we get an image as a result, not a proximal. So, is there any possibility this might be used into ADMM? I can provide the code, of course, if it may help you.

**Comment by bwohlberg** [comment]
I'm afraid I can't think of a way of making this work. The approach I suggested depends on being able to separately compute $h(\cdot)$ and $A(\cdot)$ so that the Non-linear Proximal ADMM solver can be configured so that it uses the prox of $h$ and the gradient of $A$.

**Comment by matinaz** [comment]
This is what I imagined...thank you very much, I'll try to find a way to make it work
