### ISSUE TITLE
Setting up a simple Convolution forward operator does not return

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#439]
As I try to use `SCICO` for my deblur use case and setup a simple `Convolve` linear operator for the forward model, the execution does not return after several minutes. Can you please help identify if I am doing anything obviously wrong below? 

P.S. I'm on M1 Mac running macOS 13 with python 3.10.1. 

```Python
import numpy as np 
import jax
from scico import linop

im = np.zeros((2748, 3840)).astype(float)
psf = np.zeros((2748, 3840)).astype(float)

im_jx = jax.device_put(im)  
psf_jx = jax.device_put(psf)  

C = linop.Convolve(h=psf_jx, input_shape=im_jx.shape)
```

**Comment by bwohlberg** [comment]
I don't see any obvious problems in your code. I suspect the issue you're experiencing is the same as that reported in #287, which we presume is due to a problem in `jax.scipy.signal.convolve` that occurs when using a large convolution kernel. You could try the `CircularConvolve` operator instead if that type of convolution might be acceptable.

**Comment by shnaqvi** [comment]
Yes, this solved the problem and I was able to convolve the image within 1 sec and generate expected blur result. Thanks!
```Python
import numpy as np
import jax
from scico import linop

im_jx = jax.device_put(im_sb)  
psf_jx = jax.device_put(psf2_cropped)  

C = linop.CircularConvolve(h=psf2, input_shape=im_jx.shape, h_center=[psf2.shape[0] // 2, psf2.shape[1] // 2])
y = C(im_jx)

plt.subplot(131); plt.imshow(im_jx); plt.title('Ground truth')
plt.subplot(132); plt.imshow(psf_jx); plt.title('PSF')
plt.subplot(133); plt.imshow(y); plt.title('Blurred image')
```
<img width="552" alt="image" src="https://github.com/lanl/scico/assets/4764586/76c4c08a-bdf1-4a08-86ec-a5902c93a876">
