### ISSUE TITLE
Estimating L0 parameter in AcceleratedPGM

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#447]
I've been struggling to find the suitable `Lipschitz, L0` constant for the `Accelerated PGM`. I ended up using a large `5e9` value in my case to get reasonable value. I know that it can be estimated using the largest Eigenvalue of the Hessian of the forward operator (as seen [here](https://www.epfl.ch/labs/anchp/wp-content/uploads/2018/05/solution9.pdf)). And eigenvalue could be readily computed by calling `eigsh` from the `scipy.sparse.linalg` class on the matrix's Hessian. 

However, computing the Hessian of the forward operator inherited from `LinearOperartor` gives the `__rmul__` `TypeError` 
```Python
C = linop.CircularConvolve(h=psf_jx, input_shape=im_jx.shape, h_center=[psf_jx.shape[0] // 2, psf_jx.shape[1] // 2])
C2 = C.H * C
```
```
`TypeError: Operation __rmul__ not defined between  and .`
```

Can you please tell me if there's another way to get this quick estimate of `L0` that aids in `PGM`'s convergence? I see a `step_size` parameter for this purpose, but can you share a simple example of how to use it? I see several classes inheriting from `PGMStepSize` but couldn't follow the logic of these methods. Do they estimate a step size every iteration and does that compromise speed?

**Comment by bwohlberg** [comment]
The error is because you used `C.H * C` rather than `C.H @ C`. But you don't need to implement the estimation yourself -- see `scico.linop.operator_norm`.

**Comment by shnaqvi** [comment]
Oh nice, so [this](https://scico.readthedocs.io/en/stable/_autosummary/scico.linop.html#scico.linop.operator_norm) is actually computing the sqrt. of the largest eigenvalue of the Hessian of the operator! Thanks @bwohlberg for pointing out my mistake. 

Can you also please shed a light on how can I use `PGMStepSize` in lieu of estimating L0 beforehand using the `operator_norm` as it is taking really long to run on my sum of weighted convolutions blur operator?

**Comment by bwohlberg** [comment]
You should find some relevant examples [here](https://scico.readthedocs.io/en/stable/examples/sparsecode_poisson_pgm.html).

**Comment by shnaqvi** [comment]
Thanks @bwohlberg , I was able to get clarity on using the step size from the above example.
