### ISSUE TITLE
Memory usage explosion when using AcceleratedPGM

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#448]
I have a custom forward operator defined as a sum of weighted convolutions to solve the `space-variant` deblurring problem. I am using `AcceleratedPGM` because of its fast convergence, as it doesn't require expensive computation of the proximal of L2 functional with the custom forward operator. However, it is putting a heavy toll on the memory usage by the python kernel and ends up often crashing it midway. 

Below is the sample code, where I initially loading synthetic data matrices of representative sizes and setup the optimization problem, after which the memory usage increases to `6GB`. Then we run the solver, which impressively returns 20 iterations in 4min, but the memory usage during its execution spikes to `28GB`, settling at `26GB` after it's finished. And if I rerun the cell a second time in my iPython notebook that re-sets up the problem and solves it, then it begins taking up more memory ontop of already consumed `26GB`, going upto `48GB`. So whatever memory is created is not cleared when the solver returns. 

Is there a memory leak happening somewhere and are we not cleaning up properly? Can we make it more memory efficient?

P.S. I've used `psutil` to quantify the memory usage at different stages. 

```Python
import numpy as np
import jax
from scico import linop, loss, functional
from scico.optimize import AcceleratedPGM
import psutil

init_mem = psutil.virtual_memory().free/1e9

# Sample data
im = np.random.randn(2748, 3840)
W = np.random.randn(20, *im.shape)
U = np.random.randn(20, *im.shape)

# Forward Model
C = linop.CircularConvolve(h=jax.device_put(U), input_shape=im.shape, ndims=2)
D = linop.Diagonal(jax.device_put(W))
S = linop.Sum(input_shape=D.output_shape, axis=0)

Blur = S @ D @ C

# Optimization Problem
f = loss.SquaredL2Loss(y=jax.device_put(im), A=Blur)
lbd = 5e-1  # L1 norm regularization parameter
g = lbd * functional.L21Norm()
D = linop.FiniteDifference(input_shape=im.shape, append=0)

maxiter = 20  
L0=5e9

solver_apgm = AcceleratedPGM(
    f=f,
    g=g,
    L0=L0, 
    x0=jax.device_put(im), 
    maxiter=maxiter, 
    itstat_options={"display": True, "period": 10}
)

print(f'RAM Used (GB) by process: {init_mem - (psutil.virtual_memory().free)/1e9:.3f}')
```
```
RAM Used (GB) by process: 6.263
```

```Python
x = solver_apgm.solve()
hist_apgm = solver_apgm.itstat_object.history(transpose=True)

print(f'RAM Used (GB) by process: {init_mem - (psutil.virtual_memory().free)/1e9:.3f}')
```
```
RAM Used (GB) by process: 26.810
```

**Comment by bwohlberg** [comment]
That's strange. SCICO doesn't do any explict memory allocation, so if there is a leak, it's probably in the JAX implementation. Could you try to track down where the extra memory is being used?

**Comment by shnaqvi** [comment]
How do you suggest I track it down? My macOS system activity monitor is showing that the python process is using all this memory after 2 runs of `AcceleratedPGM` solver in an iPython notebook cell, and I'm not able to see any breakdown. Could you reproduce it on your end with the above code?
<img width="527" alt="image" src="https://github.com/lanl/scico/assets/4764586/9622aab2-79b0-4db2-9dfe-a9424247f9d1">

**Comment by bwohlberg** [comment]
I'm not sure. Perhaps try `sys.getsizeof` to help figure out which object is growing in size.

**Comment by shnaqvi** [comment]
@bwohlberg , I found out that this problem was encountered by several other people and JAX community of developers added the `jax.clear_caches()` command earlier this year to address this (see [here](https://github.com/google/jax/discussions/10826)). I now run this every couple iteration and memory leak has been slowed down drastically. May be it's worth stating in `ReadMe` to prevent others from running into a similar issue.

**Comment by bwohlberg** [comment]
Thanks for pointing this out. We'll add a note to the docs.

**Comment by bwohlberg** [comment]
Could you provide a bit more detail on how you've used `jax.clear_caches`? For example, which function in the example code above are you calling it on?

**Comment by bwohlberg** [comment]
An example script in which you used `jax.clear_caches` would also be helpful.

**Comment by bwohlberg** [comment]
Closing for now since I don't have sufficient information on `jax.clear_caches` to add a coherent note to the scico docs.
