### ISSUE TITLE
Enabling use of TV prior with a forward operator with Accelerated PGM

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#450]
`Enhancement request`

My deconvolution problem of deblurring with space-variant PSF involves a forward operator that is a weighted sum of convolutions. This algorithm is presented in [Flicker & Rigaut (2005)](https://doi.org/10.1364/JOSAA.22.000504), reviewed [here](https://ujm.hal.science/ujm-00979825/file/IJCV_denis_approx_inv_shiftvariant_blur_R2.pdf) and used very recently [here](https://www.nature.com/articles/s41377-020-00403-7). Thus the final optimization problem as presented in Eq 1 of the last reference looks like this:
<img width="354" alt="image" src="https://github.com/lanl/scico/assets/4764586/f9ac53e1-cd00-490b-8533-1bc5ec836390">

Also, this last reference uses `FISTA` to speed up the problem convergence. However, I'm not able to use `FISTA` with `SCICO` because `AcceleratedPGM` does not currently support solving the problem with a forward operator and `TV` regularization. Even though `TV` prior is supported by other algorithms, like `ADMM` and `PDHG`, they have other issues of their own which prohibits me from using those. Specifically:
- `ADMM` needs a `subproblem_solver` which is not defined for a custom forward operator
- `PDHG` requires really expensive computation of l2 prox with this non-trivial forward operator through `CG`

Reformulating the problem in a way that it doesn't require complex l2 prox computation with `ProximalADMM` hasn't worked for me either, despite extensive penalty parameter tuning. And its iterations are also much slower than `APGM`. 

Thus this issue is actually an `enhancement` request to enable TV regularization with a forward operator when using `AcceleratedPGM`. @bwohlberg mentioned the fast subiteration-free parallel proximal method for TV minimization presented by [Kamilov, 2016](https://doi.org/10.1109/TIP.2016.2629449), which can be a likely contender. 

This would be a really useful addition as it would make the fastest proximal gradient method even more applicable across application domains, especially all the deblur problems which rely on TV regularization to enforce sharper edges or blockiness of image through sparsity in gradient.

**Comment by shnaqvi** [comment]
Hi @bwohlberg, took some time but here I am finally :-). I've gone through Kamilov's algorithm in detail and have implemented and tested it on synthetic blur data, getting promising reconstruction with the expected fast execution time. I've integrated it in `scico` `main` branch, creating a pull request. Would you be kind to please review it, so we can merge it to in the official pip distribution? 

P.S. I've also reached out to Ulugbek Kamilov to have this implementation reviewed but unfortunately haven't hear back from him in a week.

**Comment by bwohlberg** [comment]
Thanks! Let's move further discussion to the PR.
