### ISSUE TITLE
Reevaluate need for `ensure_on_device` function

### ISSUE THREAD

**Issue by crstngc** [lanl/scico#451]
Currently, the `ensure_on_device` function from scico/numpy/util.py interferes with deployment of SCICO with jax.distributed utils. This seems due mainly to the call to `jax.device_put` function. When distributing computations between different hosts, it is important to be able to partition data under different schemes and let jax.distributed to control it. Any outside definition of how data should be partitioned would be superseded by the local call to `jax.device_put`, which completely ignores the runtime context. A cheap fix is to remove the `jax.device_put` call, but perhaps, it would be better to completely remove the `ensure_on_device` function. Besides this, it is also pending to consider the interplay between `BlockArrays` and jax.distributed.

**Comment by bwohlberg** [comment]
Work on this in progress in branch `brendt/rm-ensure-on-device`.

In addition to calls to `ensure_on_device`, there are a few places in the code where forced conversion to a jax array is applied via other means, e.g.

https://github.com/lanl/scico/blob/349e6213ea23462d66576262ed83b12d071a8378/scico/linop/_matrix.py#L81-L87

My inclination is that conversion should only be forced where the function/class will not work if the input is a numpy array, but this is worth discussing.
