### ISSUE TITLE
Applying multiple priors with APGM solver

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#460]
I am having a difficult time finding an example where multiple priors are using to solve a problem with APGM. Is that possible by say stacking multiple operators? Specifically, I want to apply TV regularizers and a Non-Negative constraint, for deblurring problem. Thanks!

**Comment by bwohlberg** [comment]
It's not straightforward, unfortunately, but there is some work in this direction. In particular, see Yaoling Yu, "On decomposing the proximal map", Proc. NIPS, 2013.

**Comment by shnaqvi** [comment]
Oh ok, so that functionality is not implemented yet. I was wondering @bwohlberg if something like this [GeneralizedProximalGradient](https://pyproximal.readthedocs.io/en/stable/api/generated/pyproximal.optimization.primal.GeneralizedProximalGradient.html) can be implemented? It enables passing as many priors as a list and loops over their proximals. Would you mind adding it to our list of enhancements?

**Comment by bwohlberg** [comment]
Unfortunately I don't see a reference for the "generalized proximal gradient" algorithm, but I suspect it may be related to the approach proposed by Yaoling Yu, "Better Approximation and Faster Algorithm Using the Proximal Average", Proc. NIPS 2013. Agreed that it would be useful, and we can add it to the list, but realistically, it's not going to be anytime soon unless someone contributes an implementation. (For what it's worth, it looks straightforward.)

**Comment by shnaqvi** [comment]
@bwohlberg , thanks for giving it a consideration. Actually it is related to this "Proximal Splitting Methods" publication by [Combettes and Pasquett, 2011](https://link.springer.com/chapter/10.1007/978-1-4419-9569-8_10) (PDF [here](https://www.ljll.math.upmc.fr/~plc/prox.pdf)). But your [reference](https://proceedings.neurips.cc/paper/2013/hash/49182f81e6a13cf5eaa496d51fea6406-Abstract.html) also seems to be attacking the same problem of solving with non smooth regularizers. I'll add an enhancement request for it.

**Comment by bwohlberg** [comment]
Working on this. A PR should be submitted relatively soon.

**Comment by shnaqvi** [comment]
Thanks @bwohlberg , sorry I just saw this. I already created a Pull Request not knowing that you might also be actively working on it. I have tested it with our toy example with TV prior and NonNegativeIndicator prior applied and its yielding expected result. I'm sure you can highly optimize my submission, and submit a revision. 

<img width="988" alt="image" src="https://github.com/lanl/scico/assets/4764586/866a8920-c156-4a82-a1e2-9a186380893c">

<img width="523" alt="image" src="https://github.com/lanl/scico/assets/4764586/1ce39d1b-54a0-4a7b-950f-a4a00262a39f">

**Comment by bwohlberg** [comment]
My fault for not mentioning earlier that I was working on this. Thanks for the contribution. Closing this issue and referring further discussion to #465 or #466, as appropriate.
