### ISSUE TITLE
Solve AcceleratedPGM with multiple priors applied

### ISSUE THREAD

**Issue by shnaqvi** [lanl/scico#465]
Currently `AcceleratedPGM` can only solve the problem with a single loss function and a single prior. We cannot solve the composite minimization problem defined like so:

$\min_x f(x) + \bar{g}(x),\  \text{where}\ \  \bar{g}(x) = \sum_i \alpha_i g_i(x),\  \text{and}\ \  \alpha_i \ge 0, \ \sum_i \alpha_i = 1$

This has been addressed by [`Yao-Liang, 2013`](https://proceedings.neurips.cc/paper/2013/hash/49182f81e6a13cf5eaa496d51fea6406-Abstract.html) in Algorithm 1. This is an enhancement request to implement this `Proximal-Averaged AcceleratedPGM` where the proximal of the weighted priors is given by the average of their respective proximals. 

This would be extremely useful when we want to restore the noisy image with say `TV` prior while also enforcing that the result be non-zero with `NonNegativeIndicator` prior.

**Comment by bwohlberg** [comment]
See branch `brendt/proxavg` for an approach to implementing the proximal average method that does not require a new solver class. Instead, it provides a `ProximalAverage` functional that uses the proximal average when passed to the existing `PGM` or `AcceleratedPGM` solvers.

**Comment by bwohlberg** [comment]
Resolved in #469.
