### ISSUE TITLE
Additional tests for svmbir interface

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#57]
Additional tests needed to confirm that the svmbir prox solver gives the same results as a CG solve of the prox problem involving the svmbir forward and adjoint operators.

**Comment by bwohlberg** [comment]
ToDo:
- [ ]  Add an initializer parameter (default None) for `Functional.prox`
- [ ] Add passing of appropriate initializer to prox in `ADMM` (and `PGM`?)
- [ ] Add tests based on operators and CG for prox of `SVMBIRWeightedSquaredL2Loss`
- [ ] Initializers for `radon_svmbir.ParallelBeamProjector` and `SVMBIRWeightedSquaredL2Loss` should set mask radius to sufficient size to avoid masking and provide parameters that allow setting of svmbir prox solver stopping tolerance and max steps
- [ ] Choose appropriate defaults for svmbir prox solver stopping tolerance and max steps

**Comment by Michael-T-McCann** [comment]
In branch `mike/approx_prox` proxes all take `**kwargs` and ADMM passes an initial value for the prox as `v0`.
