### ISSUE TITLE
Header docs for Poisson loss example scripts

### ISSUE THREAD

**Issue by bwohlberg** [lanl/scico#82]
The header docstrings for examples `sparsecode_poisson_blkarr_pgm.py` and `sparsecode_poisson_pgm.py` are almost identical, with only one cryptic comment (*composed as a sum of the
application of individual dictionaries*) to distinguish between them. The distinction should be explained in more detail, and they should have different titles so that they don't appear to be a replication of the same example in the example index.

**Comment by tbalke** [comment]
Ok, I'll take care of it.
