### ISSUE TITLE
Output types of operators

### ISSUE THREAD

**Issue by tbalke** [lanl/scico#93]
The question got raised in https://github.com/lanl/scico/pull/88#discussion_r748994235 since the svmbir and BM3D routines returned ndarrays which may be a problematic type to pop up inside the solvers.

In general this poses the questions:
- what types do our routines return?
- do we want consistency (as in `type_in=type_out` or `type_out=Device-array-like`)

**Comment by lukepfister** [comment]
You almost certainly want `type_out=Device-array-like` in any public interfaces.  Avoid plain ndarrays as much as possible;  they will break autograd/jit/etc if they leak out.

**Comment by Michael-T-McCann** [comment]
Narrow version of the issue, change svmbir and BM3D to return jax arrays.
