### ISSUE TITLE
Positivity of svmbir prox

### ISSUE THREAD

**Issue by tbalke** [lanl/scico#95]
Currently, it is the case that when `positivity=True` in our `SVMBIRWeightedSquaredL2Loss`, the prox is a proper prox, but not of the loss of the `SVMBIRWeightedSquaredL2Loss` but of the sum of the `SVMBIRWeightedSquaredL2Loss` and an non-zero indicator.

- [x] First this should be properly documented in the code. (Addressed in 079ac16)

- [ ] Secondly, since the positivity flag may be useful, we should keep it but adjust the loss eval so that it is correct.

- [ ] Lastly, we should create some tests to check whether the corrected loss yields the same prox as the internal svmbir prox.

**Comment by smajee** [comment]
We discussed today about having a separate svmbir loss (say `SVMBIRExtendedLoss`) which allows setting the positivity and masking as directed by the user. The `SVMBIRWeightedSquaredL2Loss` loss would then implement no masking and no positivity so as to be a proper `WeightedSquaredL2Loss`.

It feels to me that there might be a lot of code/docs duplication between these two classes with some small differences. Any ideas on how to reduce the code duplication? One (albeit suboptimal) approach could be to make `SVMBIRWeightedSquaredL2Loss` inherit from `SVMBIRExtendedLoss`.

**Comment by tbalke** [comment]
I agree that the 'is-a' relationship is not very clean through inheritance.

**_But if the only concern_** is code duplication we could perhaps define generic functions outside the classes. Something like:

```python

def generic_prox(self, v, lam, positivity=None):
    pass # generic definition here

class SVMBIRExtendedLoss:
    ...
    def prox(self, v, lam):
        return generic_prox(self, v, lam, positivity=self.positivity)
    ...

class SVMBIRWeightedSquaredL2Loss(WeightedSquaredL2Loss):
    ...
    def prox(self, v, lam):
        return generic_prox(self, v, lam, positivity=False)
    ...

**Comment by bwohlberg** [comment]
That's a reasonable option, but I think deriving from a common private base class achieves the same thing in a slightly cleaner way:
```python

class _SVMBIRCommon:
    ...
    def prox(self, v, lam):
       pass # generic definition here

class SVMBIRExtendedLoss(Loss, _SVMBIRCommon):
    ...
    # no need for prox re-definition
    ...

class SVMBIRWeightedSquaredL2Loss(WeightedSquaredL2Loss, _SVMBIRCommon):
        ...
    # no need for prox re-definition
    ...
```

**Comment by tbalke** [comment]
Yep, that's better.

**Comment by smajee** [comment]
It occurred to me that `is_masked` is a property of the Projector class and not the Loss class. So, would the new SVMBIRWeightedSquaredL2Loss check whether the associated projector object has `is_masked=False` or set it False if True or something else?
